name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Installing...
      run: npm install
    - name: Building...
      run: npm run build
    - name: Testing...
      run: |
        npm run test:php
        npm run test:e2e
